travis:
  secure:
    BINSTAR_TOKEN: J6p+8uEtzu4Xmq9ZoNvX36L1jiCbpSGd/+UW/9tkN+hfr/YNNfngD7UwKiGqmYYTE1jplMrCccnoG6fc3WWmCZr9MYB1OE6YU04v8cLalCbtEQhd5kMxwGvSDBQzCFwCKLKhix/vX1UyFBR0mIOer+odQMwIdPQDT28t2ixQY65VyM93edNQKdEMKUPNnYe6wuq239p7/DeJs4OyjNj6NdjGo/8ZS0/NXqg6rVse3N6mm7M8ASiBu6wLDTAeg8U36NzVlzGKOm9kKZoLjN8hqdCY4AgVW47gTzfvzXgvBeeKCOURxPLktbJTCnLU8KPht0q0DYQTM30VCXcHgE+5V72/xX4gthnVJ5p1S/qUrVn/OJkR98A6qa+fd3byuQGmP2ypvGFdUMjK7HCNdyF8mOsiPFqAtHuyRkfefvKGJOGKeyAByzhBPiIK0FBmue5mOF3u1fnWkFnsIiaQm+PhGdo5htD8ujG5kJiwSy4bXJiOmRYqRw/WbZOhm70CA77PQJJRJ6PwLpKFLN+2WNyDgeKxW9eV3uaxJtDMFqgpZuOqJnTgXAQa3q32eYJ66a3aU1LPJ1hlBEOyjuwOKHlOXgUgb/17mQ1WSiEgI0G+m34j7dx2rDzS8ZJInyiQnGkSVYDWJJjjDzO7y7zE/hPXhZO8x3dVZIOEDhoGCkQ8eHQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
