travis:
  secure:
    BINSTAR_TOKEN: HnR2uqDPZwuoJo/PuoghLM/dBB11KpkWmqxcO3hXf8NG/GD6HzuOk35hGPbh+piMr1hog3eOeg9c8HkmjRZqhPGZxYaAuIiLRRy6enX1ObVzvWx5pHX8ixEXkFX4LUuXyC/+9TZWxQlmKJeIbTyGqQj60cFohtZ7p4+k1jAKI0b2JRY5dnEg+1bUTmugjzo3IVEoEs7DfNTEVxOEddmVvhbQ1viZwQnec46gIL49ocPNqEoURAJzz2W1Nt/AEqW4ksXHJyyjLQqa0RXa5WDqDWkRuz+84x7WfTV6q2z+vGtmq9E3qLx35y7nmtiZe1gJstU4DrS3D8CkU9TygeOWiJZMXmcXZ//us8jgB35wY8fGrqCdep1K9SnpqcrTqlxZX0KNDu9VlhF0xRLumI66gc2S4E4ems9UKABDgAgWqYC2QT37O7f5Q3wMWiqayUFxRdqO802tIm075TyYS3IUq0MacsxoWaC2iPY9d26FGzbyfigSz/fMnGvR5ylFfoFBUjr9NNsqVyG39030vMOrzneqNL5Lq/ycpwv576qIx4Zv5yJBtuVhYMTeuP8pXFxLWWGqw+aTpGS50nSAQP0DA8QZVog8dtaMBlG4+54RzNm9xVYldNn1T61epCXcJS8Jb08WjDXrMvgxzj3jevusFPdE4+PYnk+Paj03PTf/Gbs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
